### ISSUE TITLE
Stuck on "Fetching Feeds"

### ISSUE THREAD

**Issue by palradu** [grinsted/script.screensaver.feedreader#6]
Hi,

I've installed Feedreader Screensaver and added the feeds by editing the settings.xml file, but when I use the add-on as a screensaver, it stays stuck on "Fetching Feeds". I left it over night and in the morning it still hasn't fetched anything.

Think you could help?

Thank you,

Radu

**Comment by grinsted** [comment]
It should not hang, but it is impossible for me to know what goes wrong without more details. My guess is that there is something in the xml that is not as kodi assumes it to be. I think it is safer to use the settings menu instead of editing the xml manually. 

You can download the original settings.xml file from here on github.

**Comment by palradu** [comment]
OK, I will download the original file and then try to edit the feeds from the settings menu, see if that works :)

I'll get back to you once I test it out :

Thank you!
